version: '2'
services:
  bookapplication-app:
    image: bookapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookapplication-postgresql:5432/bookApplication
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://bookapplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://bookapplication-elasticsearch:9200
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    ports:
      - 8080:8080
  bookapplication-postgresql:
    extends:
      file: postgresql.yml
      service: bookapplication-postgresql
  bookapplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: bookapplication-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
